name: c_binaries

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: apt update
      run: sudo apt-get update
    - name: add nasm
      run: sudo apt-get install -y nasm
    - name: Run tests
      run: cd nasm && make test_mains
    - name: linkable binary
      run: cd nasm && make bin && ./linkable_binary.out
  test-macos-xcode_15_2-intel:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - name: add nasm
      run: brew install nasm
    - name: Run tests
      run: cd nasm && make test_mains
    # binary segfaults on macos catalina without 16-byte-alignment for syscalls (stack_not_16_byte_aligned_error)
    - name: linkable binary
      run: cd nasm && make bin && ./linkable_binary.out
  test-macos-xcode_16-emulated:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: add nasm
      run: brew install nasm
    - name: Run tests
      run: cd nasm && make test_mains
    # binary segfaults on gha arm64 when not running with macos-14/latest
    - name: linkable binary
      run: cd nasm && make bin && ./linkable_binary.out