name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: add nasm
      run: sudo apt-get update -y; sudo apt-get install -y nasm
    - name: Run tests
      run: cd use-from-rust && cargo test --target x86_64-unknown-linux-gnu